# Generated by Django 5.0.6 on 2024-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='assets/Illustration/default.jpg', upload_to='assets/Illustration'),
        ),
    ]
