# Generated by Django 5.0.4 on 2024-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isekai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='default_cover.jpg', upload_to='post_covers'),
        ),
    ]
