# Generated by Django 5.0.4 on 2024-05-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isekai', '0003_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='post_covers'),
        ),
    ]
